# Generated by Django 4.2.6 on 2023-10-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='start_bid',
        ),
        migrations.AddField(
            model_name='listing',
            name='highest_bid',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.bid'),
        ),
    ]
