# Generated by Django 4.2.6 on 2023-10-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_bid_listing_remove_listing_start_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
