# Generated by Django 4.2.6 on 2023-10-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listing_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
