# Generated by Django 4.2.6 on 2023-10-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_photo_listing_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.CharField(max_length=2048),
        ),
    ]
