# Generated by Django 4.2.6 on 2023-10-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='desc',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(default=None, max_length=2048),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ManyToManyField(default=None, related_name='listings', to='auctions.category'),
        ),
    ]
