# Generated by Django 4.2.6 on 2023-10-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_category_alter_listing_desc_alter_listing_img_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='categories',
        ),
    ]
