# Generated by Django 4.2.6 on 2023-10-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_listing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, related_name='listings', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(blank=True, default=None, max_length=2048),
        ),
    ]
