# Generated by Django 4.2.6 on 2023-10-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_listing_categories_alter_listing_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
