# Generated by Django 4.2.6 on 2023-10-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0015_alter_listing_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="num_bids",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
