# Generated by Django 4.2.6 on 2023-10-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0017_alter_listing_highest_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="highest_bid",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.bid",
            ),
        ),
    ]
