# Generated by Django 4.2.6 on 2023-10-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_listing_highest_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='highest_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='num_bids',
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Bids', to='auctions.listing'),
        ),
    ]
