# Generated by Django 4.2.6 on 2023-10-21 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_remove_bid_listing_listing_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='watched', to=settings.AUTH_USER_MODEL),
        ),
    ]
