# Generated by Django 4.2.6 on 2023-10-29 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 10, 56, 33, 620482, tzinfo=datetime.timezone.utc)),
        ),
    ]
