# Generated by Django 4.2.6 on 2023-10-29 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 12, 17, 5, 68985, tzinfo=datetime.timezone.utc)),
        ),
    ]
