# Generated by Django 4.2.6 on 2023-10-29 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 12, 38, 24, 368572, tzinfo=datetime.timezone.utc)),
        ),
    ]
